### ISSUE TITLE
Exception: Unsupported device type: mkl When using roolUL-IntelArc-ArchLinux.

### ISSUE THREAD

**Issue by tb115** [JT-Gresham/AI-IntelArc-ArchLinux#1]
Thank you for your work.
Please help me work through this.

os: endeavouros (arch based)
gpu: arc a770m
installed packages: intel-compute-runtime intel-graphics-compiler ocl-icd opencl-headers 
I initially got an error "libze_loader.so.1: cannot open shared object file: No such file or directory" i fixed it by installing level-zero-loader

According to intel-gpu-top: Intel Dg2 (Gen12)

When using roolUL-IntelArc-ArchLinux.
default settings: openvino, 2 execution threads, use defult det size.
When i change any of the settings, there is no difference i still get the mkl error

console log:
"
[endeavouros@endeavouros roopUL-IntelArc-ArchLinux]$ ./roopUL-Start.sh 
- httpx - INFO - HTTP Request: GET https://api.gradio.app/gradio-messaging/en "HTTP/1.1 200 OK"
No CLI args supported - use Settings Tab instead
Using provider ['OpenVINOExecutionProvider'] - Device:mkl
Running on local URL:  http://127.0.0.1:7860
 - httpx - INFO - HTTP Request: GET http://127.0.0.1:7860/startup-events "HTTP/1.1 200 OK"
 - httpx - INFO - HTTP Request: HEAD http://127.0.0.1:7860/ "HTTP/1.1 200 OK"

To create a public link, set `share=True` in `launch()`.
 - httpx - INFO - HTTP Request: GET https://checkip.amazonaws.com/ "HTTP/1.1 200 "
 - httpx - INFO - HTTP Request: GET https://api.gradio.app/pkg-version "HTTP/1.1 200 OK"
Forcing CPU for Face Analysis
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
mbind failed: Invalid argument
Sorting videos/images
Creating 169891092_867938403755315_130821676043284507_n__temp.mkv with 30.0 FPS...
['ffmpeg', '-hide_banner', '-hwaccel', 'auto', '-y', '-loglevel', 'error', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-s', '640x1136', '-pix_fmt', 'bgr24', '-r', '30.0', '-an', '-i', '-', '-vcodec', 'libx265', '-crf', '14', '-vf', 'colorspace=bt709:iall=bt601-6-625:fast=1', '-pix_fmt', 'yuv420p', '/home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/output/169891092_867938403755315_130821676043284507_n__temp.mkv']
Processing:   0%|                                                                 | 0/443 [00:00<?, ?frames/s]Forcing CPU for Face Analysis
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
model ignore: /home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/models/buffalo_l/genderage.onnx genderage
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Processing:   5%|▋            | 24/443 [00:01<00:31, 13.39frames/s, memory_usage=04.46GB, execution_threads=2]
Traceback (most recent call last):
  File "/home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/roopUL-IntelArc-ArchLinux_env/lib/python3.10/site-packages/gradio/queueing.py", line 566, in process_events
    response = await route_utils.call_process_api(
  File "/home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/roopUL-IntelArc-ArchLinux_env/lib/python3.10/site-packages/gradio/route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/endeavouros/roopUL-Innuc12snki72telArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/roopUL-IntelArc-ArchLinux_env/lib/python3.10/site-packages/gradio/blocks.py", line 1847, in process_api
    result = await self.call_function(
  File "/home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/roopUL-IntelArc-ArchLinux_env/lib/python3.10/site-packages/gradio/blocks.py", line 1445, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/roopUL-IntelArc-ArchLinux_env/lib/python3.10/site-packages/gradio/utils.py", line 629, in async_iteration
    return await iterator.__anext__()
  File "/home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/roopUL-IntelArc-ArchLinux_env/lib/python3.10/site-packages/gradio/utils.py", line 622, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/roopUL-IntelArc-ArchLinux_env/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/roopUL-IntelArc-ArchLinux_env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/roopUL-IntelArc-ArchLinux_env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/roopUL-IntelArc-ArchLinux_env/lib/python3.10/site-packages/gradio/utils.py", line 605, in run_sync_iterator_async
    return next(iterator)
  File "/home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/roopUL-IntelArc-ArchLinux_env/lib/python3.10/site-packages/gradio/utils.py", line 788, in gen_wrapper
    response = next(iterator)
  File "/home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/ui/tabs/faceswap_tab.py", line 621, in start_swap
    batch_process_regular(list_files_process, mask_engine, clip_text, processing_method == "In-Memory processing", imagemask, num_swap_steps, progress, SELECTED_INPUT_FACE_INDEX)
  File "/home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/roop/core.py", line 219, in batch_process_regular
    batch_process(files, use_new_method)
  File "/home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/roop/core.py", line 320, in batch_process
    process_mgr.run_batch_inmem(v.filename, v.finalname, v.startframe, v.endframe, fps,roop.globals.execution_threads, skip_audio)
  File "/home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/roop/ProcessMgr.py", line 296, in run_batch_inmem
    future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/roop/ProcessMgr.py", line 228, in process_videoframes
    resimg = self.process_frame(frame)
  File "/home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/roop/ProcessMgr.py", line 330, in process_frame
    num_swapped, temp_frame = self.swap_faces(frame, temp_frame)
  File "/home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/roop/ProcessMgr.py", line 396, in swap_faces
    temp_frame = self.process_face(self.options.selected_index, face, temp_frame)
  File "/home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/roop/ProcessMgr.py", line 553, in process_face
    swap_frame = p.Run(inputface, target_face, swap_frame)
  File "/home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/roop/processors/FaceSwapInsightFace.py", line 49, in Run
    io_binding.bind_output("output", self.devicename)
  File "/home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/roopUL-IntelArc-ArchLinux_env/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 605, in bind_output
    get_ort_device_type(device_type, device_id),
  File "/home/endeavouros/roopUL-IntelArc-ArchLinux/ainstalled/roopUL-IntelArc-ArchLinux/roopUL-IntelArc-ArchLinux_env/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 32, in get_ort_device_type
    raise Exception("Unsupported device type: " + device_type)
Exception: Unsupported device type: mkl
"

**Comment by JT-Gresham** [comment]
Honestly...there's several issues now. I'm trying IPEX-LLM[xpu] along with a hodge-podge of mkl, sycl, oneapi...you name it.  Something has changed in the last month or so that broke the version I had working. I'm now getting an error from torch regarding an unidentified FLAG reference.  It might be awhile before I actually put out a release...this is all a WIP.  I'm thinking that maybe Intel added some reference to a windows dll...just a guess.  Of course, that directly would flip those of us on Linux the proverbial bird.
